apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-api
  labels:
    app: feed-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feed-api
  template:
    metadata:
      labels:
        app: feed-api
    spec:
      containers:
        - name: feed-api
          image: byblix/project3_feed-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: k8s-variables
